### ISSUE TITLE
When changes will be released, update documentation

### ISSUE THREAD

**Issue by Audrunas** [devbridge/BetterCMS#1329]
- [x] HTML content API update (#1321)
- [x] Blog posts API update (#1310)
- [x] If this feature will be implemented: #1173, add also to the documentation
- [x] Multiligual widgets API #1333

Mention, if HTML is null, markdown and text is generated from the property OriginalText
