### ISSUE TITLE
Update CMS UI

### ISSUE THREAD

**Issue by smikulenas** [devbridge/BetterCMS#1393]
- [x] Update Settings modal (including all sub-tabs) (is blocked by #1395, #1405)
 - [x] Update messaging (is blocked by #1406)
 - [x] Update Control panel (is blocked by #1394, #1435)
 - [x] Update Path Navigation control (is blocked by #1396)
 - [x] Update Page creation modal (is blocked by #1397)
 - [x] Update Page Properties modal (is blocked by #1398)
 - [x] Update SEO modal
 - [x] Update Delete Page modal
 - [x] Update Blog post edit modal
 - [x] Update Clone Page modal
 - [x] Update Translate Page modal
 - [x] Update new page placing to sitemap modal (is blocked by #1399)
 - [x] Update Sitemap Edit modal (is blocked by #1400)
 - [x] Update content creation/edit modal (is blocked by #1401)
 - [x] Update widget selection modal (is blocked by #1402)
 - [x] Update image selection modal
 - [x] Update file selection modal
 - [x] Update history dialog (is blocked by #1407)
 - [x] Update page structure manager modal (is blocked by #1403)

Initial UI version: https://github.com/devbridge/BetterCMS/issues/1397#issuecomment-152127529

Review #1299, #1253, #1369, #863.

**Comment by smikulenas** [comment]
Fix available in 2.0.0-preview1+
